### ISSUE TITLE
GameUpdater syntax error

### ISSUE THREAD

**Issue by PinyaGit** [mbpictures/GameUpdater#5]
![изображение](https://user-images.githubusercontent.com/39755512/177058221-15ea9229-b74e-4175-979d-dbafe4b208d1.png)

I wrote all the correct paths on the local PC and on the server from where to download. As a result, there is an incomprehensible long path and the program stops. If you do build - the launcher just does not start. Can you get the procedure? did everything according to readme

**Comment by PinyaGit** [comment]
I think I got it. You just need to put the two files in a folder.

update.xml
GameUpdater.ini

but Publish build It still won't start

**Comment by mbpictures** [comment]
You need further investigation or can I close the issue?

**Comment by PinyaGit** [comment]
sure i need. the program just hangs idle

**Comment by PinyaGit** [comment]
I think you showed the mp4 link, is it still there? I'll try to make sure it's not a bug in the web server.

**Comment by PinyaGit** [comment]
never mind, I used the link to file-examples.com and it works. I guess I just need to solve the problem with my hosting. The problem is not relevant
