### ISSUE TITLE
manifest.exe and large .xml files

### ISSUE THREAD

**Issue by PinyaGit** [mbpictures/GameUpdater#6]
I'm probably boring by now, but there are some things that don't work or don't work as well as they should. :D

about manifest.exe :

Using -> ```ManifestTool.exe -f YOUR_FOLDER -v 1.0.0 -d 0.0.0 -u http://YOUR_URL.COM ```

files are generated on the specified path, and if you run the launcher - the files are downloaded to the same directory.
For example, I generate path ```C:\wamp64\www\pinserv-site\testgame```
I get ```<location>C:\wamp64\www\pinserv-site\testgame\%FILE_NAME%</location>```      <--- (in update.xml)

then, If I run it on the PC, where I generated, the launcher said that all the files are present no need to download anything - logical.
or I get a syntax error like last time.
If I run on another PC - the launcher just freeze and does not work.

OK, found a solution to download files in the folder where it is running if you change the path a little bit

```<location>C:\wamp64\www\pinserv-site\testgame\%FILE_NAME%</location>``` -----> ```<location>\testgame\%FILE_NAME%</location>```

After starting the launcher creates a folder ```testgame``` and downloads everything there.

And now for the best part:

If I use the generated 1 file, the launcher downloads it without any problems. Described above. 

BUT

If I use the generated file of 68000 lines, (about 8000 files), I get the next error:
![изображение](https://user-images.githubusercontent.com/39755512/177366624-3b549267-1bea-40df-b659-c810b6390e2d.png)

I'm silent about the 700k lines, but the launcher is able to check such a large number of files or not?

**Comment by PinyaGit** [comment]
![изображение](https://user-images.githubusercontent.com/39755512/177388808-d0a4ac12-3bf7-4a8f-99d5-e3787926c7f8.png)
noticed that both fields lead to a path, not a link

**Comment by mbpictures** [comment]
No worries, I don't forget your issue. I'm just in trouble due exam phase. So please hang tight! ;)

**Comment by PinyaGit** [comment]
Oh, I'm not rushing it. Good luck ;D

**Comment by mbpictures** [comment]
For the issue with the path location: I suggest you to run the ManifestTool.exe from the relative location where the GameUpdater.exe will be. So e.g. you want this structure on the clients using the Updater:
```
--- root/
 --- GameUpater.exe
 --- GameUpdater.ini
 --- ...
 ---  gamefiles/
   --- ...
```

My advice is to create folder next to the ManifestTool.exe file with the name "gamefiles" and copy all your files into that folder. Than run the ManifestTool.exe with a **relative** path (```-f gamefiles```) and all your paths will be relative to your current location in the update.xml file.

The second thing you mentioned should be fixed in the current master branch. I also added error handling when file download is not possible (e.g. 404 error).

**Comment by PinyaGit** [comment]
I read the solution, now fixing my stuff a bit. I'll check as soon as I get my hosting back. Thank you!

**Comment by PinyaGit** [comment]
No, it just doesn't work. After the -f gamefiles parameter, it just duplicates that folder in the .xml twice. Accordingly, the launcher run and says it can not find the path. After running the corrected path (removing unnecessary gamefiles in the path) the launcher just doesn't start, but there is an empty folder gamefiles next to the .exe launcher. Honestly I no longer have the strength to try to do something here. Thank you very much for your responsiveness to the problems, but without a video or a specific setup step by step - I do not get anything.

**Comment by mbpictures** [comment]
Hey @PinyaGit sorry for replying that late. Do you still experience issues? Please tell me, what exactly you are doing (which files, in which folders, which command, ...), what you are expecting to happen and what happens.

**Comment by PinyaGit** [comment]
I have already deleted all the work and try to make patches using zip files. I will try your launcher again a little later and describe in detail what is wrong.ヽ(・∀・)ﾉ

**Comment by PinyaGit** [comment]
Well. Let's start at the beginning.
What we have:

- Website
- directories with files inside
- Https certificates and working access from outside.

1) download the "visual 2022 community" without any add-ons
2) git clone and unpack "https://github.com/mbpictures/GameUpdater" in any directory
3) Try opening GameUpdater.sln and see that wix is required - Install this.
4) Also install development of classic .NET applications
5) Reopen project and install .NET Core 3.1 (LTS) too.
6) Reload projects with dependencies and finally we're done. You are ready to work

}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+{
/// Let's build the ManifestTool ///

1) cmd
2) cd /d E:\GameUpdater-master\
3) dotnet build

build error - install  WiX v3.11.2
https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm

4) build again - boom! DONE!
}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+{


The website folder is located at the following path:
C:\wamp64\www\pinserv-site\FullGameDirectory

/// Let's make update.xml ///

1) cd E:\GameUpdater-master\ManifestTool\bin\Debug\netcoreapp3.1\
2) ManifestTool.exe -f C:\wamp64\www\pinserv-site\FullGameDirectory\ -v 1.0.1 -d 1.0.0 -u https://SITE/FullGameDirectory/
3) we get the .xml file, great!

((((Note that the tool and the game files are on different partitions))))
}+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+{


1) Copy the .xml file to the root of the site
(C:\wamp64\www\pinserv-site\update.xml)

2) cd E:\GameUpdater-master\GameUpdater
3) dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:TrimUnusedDependencies=true --self-contained false 

Now we have launcher build at the following path:
E:\GameUpdater-master\GameUpdater\bin\Release\netcoreapp3.1\win-x64

4) Copy the GameUpdater.ini file into the same folder
5) edit "ServerManifest=https://site/update.xml
6) run GameUpdater.exe

I get a new weird error where the path from the C and E drive is duplicated
Currently stuck at this point.
![изображение](https://user-images.githubusercontent.com/39755512/190465449-7223aaa6-4144-40ce-aa58-513565ce34d8.png)

**Comment by PinyaGit** [comment]
UP:
If I run the same launcher through another PC, I get a slightly different error, but the same general sense.

![изображение](https://user-images.githubusercontent.com/39755512/190470360-9ac4102d-6c42-45c9-86be-c6c66c80fd64.png)

**Comment by mbpictures** [comment]
Thanks for the detailed description!
First things first: I don't speak Russian, so I guess you have to translate the error message (if this is important).
Second: Please copy the Manifest RELATIVE to the location, where you expect the files to be downloaded to.
E.g. ```C:\wamp64\www\pinserv-site\FullGameDirectory``` is the directory where you game files are located at and you want, that the final folder structure is:
- root directory
   - GameUpdater.exe
   - [FILES_OF_UPDATER]
   - FullGameDirectory
       - [FILES_OF_YOUR_GAME]

then please copy the ManifestTool.exe to ```C:\wamp64\www\pinserv-site``` and run the command with ```ManifestTool.exe -f FullGameDirectory [...OTHER_ARGUMENTS]```

**Comment by PinyaGit** [comment]
well, something new. If I understand correctly, the file structure now looks like this:
![изображение](https://user-images.githubusercontent.com/39755512/190475322-65ce4051-769e-45f1-b631-71d6d4793bba.png)
manifest also made a strange path to the game files, twice copying the name of the folder
![изображение](https://user-images.githubusercontent.com/39755512/190475575-c759a99f-1126-480b-963c-d67c05c8157e.png)

I fixed it myself by deleting the extra one and the update seemed to start downloading, but very slowly.

UP:
deleting the folder and checking the files sends the launcher into a long freeze, then it quickly downloads the files again. I need to simulate several situations with a larger game client.

UPx2:
Full restart of the Launcher now does not start at all

**Comment by mbpictures** [comment]
The Manifest isn't duplicating the Folder Name. It appends the local folder to the URL (https://site/FullGameDirectory/) you provided. So the local FullGameDirectory is appended to the FullGameDirectory of your webspace. Removing the "FullGameDirectory" of the provided will solve the "issue".
The other thing: I recommend you to use the ZIP flag if you have such a large amount of files.

**Comment by PinyaGit** [comment]
is there a way to make the directory as like...?:

    root directory
        GameUpdater.exe
        [FILES_OF_UPDATER]
        [FILES_OF_YOUR_GAME]

**Comment by PinyaGit** [comment]
btw If you change \ to /, the launcher at least starts, but reports an error. It draws them in different directions. What command should I run to generate the whole root file?

**Comment by mbpictures** [comment]
When you don't want that the game files are placed in a sub-directory relative to the GameUpdater.exe simply put the ManifestTool.exe in the ```C:\wamp64\www\pinserv-site\FullGameDirectory``` folder

**Comment by PinyaGit** [comment]
`ManifestTool.exe ./ --sha1 false -v 1.0.0 -u http://pinserv.ru/FullGameDirectory`
will it look like that?

**Comment by PinyaGit** [comment]
No, it doesn't work that way... I'm sorry, it's probably too complicated for me. Although using the zip in another launcher did not have this problem.

**Comment by mbpictures** [comment]
```ManifestTool.exe -f ./ --zip -v 1.0.0 -u http://pinserv.ru/FullGameDirectory```
Should be the command of your choice.
What's the problem at your end?

**Comment by PinyaGit** [comment]
I double-checked absolutely everything. It doesn't work the way it's supposed to.
