### ISSUE TITLE
VS 2022

### ISSUE THREAD

**Issue by DragonSlayer62** [mbpictures/GameUpdater#8]
I cant seem to get this program to work with vs 2022.

**Comment by mbpictures** [comment]
Hi! Thanks for the report, can you please describe where exactly you have Problems? Do you experience issues while opening the solution or while building? Which Build-Config do you use? Can you please attach error logs? Feel free to add as many information, so I can investigate the issue. Thank you already for your work!

**Comment by mbpictures** [comment]
I tried to reproduce it and I saw, that VS throws an error, that it can't read the .wixproj files. Updating VS and installing the WiX Toolkit plugin (https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension) fixed it for me. Please check, if you installed the extension, and let me know if you have further issues!
